name: Daily Check
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
env:
  RUST_LOG: info

jobs:
  run:
    name: Run Updater
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set-up Rust Toolchain
        run: rustup toolchain install stable --profile minimal
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Cargo Build
        uses: clechasseur/rs-cargo@v2
        with:
          command: build
          args: --release
      - name: Cargo Run
        uses: clechasseur/rs-cargo@v2
        continue-on-error: true
        with:
          command: run
          args: --release
