name: "Daily Check"
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
env:
  RUST_LOG: info

jobs:
  get:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Set-up Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Cargo Run
        uses: clechasseur/rs-cargo@v2
        with:
          command: run
          args: --release
